export const EntryData = [
  {
    id: 1,
    date: 14,
    month: "May",
    color: "#abd194",
    title: "It was a good day",
    description: "* Insert text here *",
  },
  {
    id: 2,
    date: 24,
    month: "May",
    color: "#ddd38e",
    title: "It was a good day",
    description: "* Insert text here *",
  },
  {
    id: 3,
    date: 27,
    month: "May",
    color: "#cae1fc",
    title: "It was a good day",
    description: "* Insert text here *",
  },
  {
    id: 4,
    date: 17,
    month: "May",
    color: "#f5baee",
    title: "It was a good day",
    description: "* Insert text here *",
  },
  {
    id: 5,
    date: 31,
    month: "May",
    color: "#dd9297",
    title: "It was a good day",
    description: "* Insert text here *",
  },
  {
    id: 6,
    date: 12,
    month: "May",
    color: "#ddd492",
    title: "It was a good day",
    description: "* Insert text here *",
  },
];
